#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require 'vrlib'

#make program output in real time so errors visible in VR.
STDOUT.sync = true
STDERR.sync = true

#everything in these directories will be included
my_path = File.expand_path(File.dirname(__FILE__))
require_all Dir.glob(my_path + "/bin/**/*.rb")

x = ReportMarkerGUI.new
x.show


